@echo off
setlocal EnableDelayedExpansion
REM v5.1: chcp 65001 (UTF-8 console) so paths with non-ASCII usernames
REM   (e.g. C:\Users\<Chinese name>) parse correctly; console codepage stays
REM   changed for this window only. All script content remains ASCII.
chcp 65001 >nul
REM ============================================================
REM Hindsight Windows service installer - v5 PARAMETERIZED
REM v5 (2026-09-06): parameterized (no hardcoded paths/key/
REM   endpoint) + --rehearse read-only rehearsal mode.
REM   Param source priority: 1) params file generated by
REM   check-env.mjs (hindsight-params.cmd), 2) defaults derived
REM   from USERPROFILE/APPDATA (cross-machine portable).
REM   Key resolution (never persisted to disk): env var
REM   ZAI_API_KEY or ZHIPU_API_KEY > HKCU\Environment (same
REM   names) > interactive prompt during install.
REM USAGE: install-hindsight-service.cmd [--rehearse] [paramsfile]
REM   --rehearse : resolve and print params + planned actions,
REM                change nothing, no elevation needed.
REM NOTE: this file is ASCII-only BY DESIGN (cmd.exe parses
REM   batch in ANSI codepage; UTF-8 Chinese comments break it).
REM History lessons (keep):
REM   v2 (2026-09-03): BSOD 0xEF fix - findstr patterns with
REM     spaces MUST use /c: (OR-split matched every LISTENING
REM     line; taskkill /F killed SYSTEM processes). taskkill
REM     ALWAYS needs a process-name whitelist.
REM   v3 (2026-09-03): service env MUST include
REM     PYTHONUTF8=1 PYTHONIOENCODING=utf-8 (Chinese Windows
REM     GBK codepage crashes on Unicode banner; Git Bash manual
REM     runs masked this via profile-exported vars).
REM Fresh-machine prerequisites (before real install):
REM   1) install hindsight-api so HINDSIGHT_EXE exists
REM      (uv tool install hindsight-api hindsight-zcode)
REM   2) nssm.exe -> %HSDIR%\bin\ (download from nssm.cc, record
REM      SHA256; see docs/16 section 3 acquisition table)
REM   3) models bge-m3 + bge-reranker-base -> %MODELS_DIR%\
REM      (ModelScope predownload, sentinel = config.json in dir;
REM      see docs/16 section 3 acquisition table)
REM   4) after FIRST service start, run fix-pg0-junction.cmd
REM      (same directory, parameterized) to pin pg0 data dir
REM      back to the user profile (Known-Folders quirk).
REM Run real install in an ELEVATED terminal. Idempotent.
REM ============================================================

REM ---- arg parsing ----
set "REHEARSE=0"
set "PARAMFILE=%~dp0hindsight-params.cmd"
:parse
if "%~1"=="" goto parsed
if /i "%~1"=="--rehearse" (set "REHEARSE=1") else (set "PARAMFILE=%~1")
shift
goto parse
:parsed

REM ---- defaults (portable, derived from USERPROFILE/APPDATA) ----
set "HSDIR=%USERPROFILE%\.hindsight"
set "NSSM=%HSDIR%\bin\nssm.exe"
set "HINDSIGHT_EXE=%APPDATA%\uv\tools\hindsight-api\Scripts\hindsight-api.exe"
set "LOGDIR=%HSDIR%\logs"
set "MODELS_DIR=%HSDIR%\models"
set "LLM_BASE_URL=https://api.z.ai/api/coding/paas/v4"
set "LLM_MODEL=glm-5.3-flash"
set "API_PORT=8888"
set "PYTHON_UTF8=1"

REM ---- params file overlay ----
if exist "!PARAMFILE!" (
  call "!PARAMFILE!"
  echo [params] loaded: !PARAMFILE!
) else (
  echo [params] not found: !PARAMFILE! - using derived defaults
)

REM ---- key resolution (runtime only, never persisted) ----
set "ZKEY=%ZAI_API_KEY%"
if "!ZKEY!"=="" set "ZKEY=%ZHIPU_API_KEY%"
if "!ZKEY!"=="" for /f "tokens=3" %%K in ('reg query HKCU\Environment /v ZAI_API_KEY 2^>nul ^| findstr /i "REG_SZ"') do set "ZKEY=%%K"
if "!ZKEY!"=="" for /f "tokens=3" %%K in ('reg query HKCU\Environment /v ZHIPU_API_KEY 2^>nul ^| findstr /i "REG_SZ"') do set "ZKEY=%%K"

if "!REHEARSE!"=="1" goto rehearse

REM ---- 0) elevation and presence checks ----
net session >nul 2>&1
if errorlevel 1 (echo [FAIL] run in an ADMINISTRATOR terminal ^(or use --rehearse^). & pause & exit /b 1)
if "!ZKEY!"=="" (
  echo [input] API key not found in env/registry. Enter it now ^(used in this process only^):
  set /p "ZKEY=ZAI key> "
  if "!ZKEY!"=="" (echo [FAIL] empty key, abort. & exit /b 1)
)
if not exist "!NSSM!" (echo [FAIL] nssm.exe missing: !NSSM! & pause & exit /b 1)
if not exist "!HINDSIGHT_EXE!" (echo [FAIL] hindsight-api.exe missing: !HINDSIGHT_EXE! - install hindsight-api first. & pause & exit /b 1)
if not exist "!MODELS_DIR!\bge-m3\config.json" (echo [FAIL] bge-m3 model incomplete: !MODELS_DIR!\bge-m3 ^(config.json missing - redownload from ModelScope^) & pause & exit /b 1)
if not exist "!MODELS_DIR!\bge-reranker-base\config.json" (echo [FAIL] bge-reranker model incomplete: !MODELS_DIR!\bge-reranker-base ^(config.json missing^) & pause & exit /b 1)
if not exist "!LOGDIR!" mkdir "!LOGDIR!"
echo [1/5] params and key ready

REM ---- 1) stop old instance (v2 iron rules: port-precise + name whitelist) ----
powershell -NoProfile -Command "Get-NetTCPConnection -LocalPort !API_PORT!,5432 -State Listen -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique | ForEach-Object { $p = Get-Process -Id $_ -ErrorAction SilentlyContinue; if ($p -and $p.ProcessName -match 'hindsight|python|postgres') { Write-Host ('  stopping ' + $p.ProcessName + ' (PID ' + $_ + ')'); Stop-Process -Id $_ -Force } }"
echo [2/5] old instance stopped ^(whitelist-filtered, ports !API_PORT!/5432 only^)

REM ---- 2) idempotent reinstall ----
"!NSSM!" stop hindsight >nul 2>&1
"!NSSM!" remove hindsight confirm >nul 2>&1
"!NSSM!" install hindsight "!HINDSIGHT_EXE!"
"!NSSM!" set hindsight AppDirectory "!HSDIR!"
REM RERANKER_MAX_CANDIDATES=30: official default 300 rerank pairs costs ~26s per recall on
REM CPU-only machines (ARM64/no CUDA) and busts the 10s hook timeout (harness repo docs/08
REM field log, entry 4). GPU machines may raise it for better ranking quality.
"!NSSM!" set hindsight AppEnvironmentExtra HF_ENDPOINT=https://hf-mirror.com HINDSIGHT_API_MODEL_INIT_TIMEOUT=900 HINDSIGHT_API_LLM_PROVIDER=openai HINDSIGHT_API_LLM_API_KEY=!ZKEY! HINDSIGHT_API_LLM_BASE_URL=!LLM_BASE_URL! HINDSIGHT_API_LLM_MODEL=!LLM_MODEL! HINDSIGHT_API_EMBEDDINGS_LOCAL_MODEL=!MODELS_DIR!\bge-m3 HINDSIGHT_API_RERANKER_LOCAL_MODEL=!MODELS_DIR!\bge-reranker-base HINDSIGHT_API_RERANKER_MAX_CANDIDATES=30 USERPROFILE=%USERPROFILE% HOME=%USERPROFILE% PYTHONUTF8=!PYTHON_UTF8! PYTHONIOENCODING=utf-8 >nul
"!NSSM!" get hindsight AppEnvironmentExtra | findstr /c:"PYTHONUTF8=1" >nul || (echo [FAIL] PYTHONUTF8 not applied to service env - DO NOT START & pause & exit /b 1)
"!NSSM!" set hindsight AppStdout "!LOGDIR!\service-out.log" >nul
"!NSSM!" set hindsight AppStderr "!LOGDIR!\service-err.log" >nul
"!NSSM!" set hindsight AppRotateFiles 1 >nul
"!NSSM!" set hindsight AppRotateOnline 1 >nul
"!NSSM!" set hindsight AppRotateBytes 10485760 >nul
"!NSSM!" set hindsight AppStdoutCreationDisposition 4 >nul
"!NSSM!" set hindsight AppStderrCreationDisposition 4 >nul
"!NSSM!" set hindsight AppThrottle 30000 >nul
"!NSSM!" set hindsight Start SERVICE_AUTO_START >nul
echo [3/5] service registered ^(env pinned, 10MB log rotation, throttle 30s, auto-start^)

REM ---- 3) start and report ----
"!NSSM!" start hindsight
timeout /t 8 /nobreak >nul
echo [4/5] service started. State:
sc query hindsight | findstr /i "STATE"
echo [5/5] waiting for app init ^(local models load ~60-90s^)...
echo       logs: !LOGDIR!\service-out.log / service-err.log
echo.
echo NEXT: after ~90s verify in any terminal:
echo   curl -s -o nul -w "HTTP %%{http_code}\n" http://localhost:!API_PORT!/v1/default/banks
echo   ^(expect HTTP 200^)
pause
exit /b 0

:rehearse
echo ===== REHEARSE read-only preview (changes nothing) =====
if exist "!PARAMFILE!" (echo params file  : !PARAMFILE! [loaded]) else (echo params file  : !PARAMFILE! [not found, defaults in use])
if exist "!NSSM!" (echo nssm.exe         : OK   !NSSM!) else (echo nssm.exe         : MISSING   !NSSM!)
if exist "!HINDSIGHT_EXE!" (echo hindsight-api.exe : OK   !HINDSIGHT_EXE!) else (echo hindsight-api.exe : MISSING   !HINDSIGHT_EXE!)
if exist "!MODELS_DIR!\bge-m3\config.json" (echo bge-m3 model     : OK) else (if exist "!MODELS_DIR!\bge-m3" (echo bge-m3 model     : INCOMPLETE dir exists but config.json missing: !MODELS_DIR!\bge-m3) else (echo bge-m3 model     : MISSING   !MODELS_DIR!\bge-m3))
if exist "!MODELS_DIR!\bge-reranker-base\config.json" (echo bge-reranker     : OK) else (if exist "!MODELS_DIR!\bge-reranker-base" (echo bge-reranker     : INCOMPLETE dir exists but config.json missing) else (echo bge-reranker     : MISSING   !MODELS_DIR!\bge-reranker-base))
echo HSDIR            = !HSDIR!
echo LOGDIR           = !LOGDIR!
echo MODELS_DIR       = !MODELS_DIR!
echo LLM_BASE_URL     = !LLM_BASE_URL!
echo LLM_MODEL        = !LLM_MODEL!
echo API_PORT         = !API_PORT!
if "!ZKEY!"=="" (
  echo ZKEY             = not in env/registry; will prompt interactively on real install
) else (
  echo ZKEY             = !ZKEY:~0,6!****** ^(masked; source: env var or registry^)
)
echo.
echo Real install would: 1^) stop old instance ^(whitelist^)  2^) reinstall NSSM service hindsight ^(env pinned + rotation + auto-start^)  3^) start + health check
echo To install for real: run this script WITHOUT --rehearse in an elevated terminal.
exit /b 0
